# Generated by Django 4.1.1 on 2022-12-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
