# Generated by Django 4.1.1 on 2022-12-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('des', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('image', models.FileField(upload_to='crud_app/static')),
            ],
        ),
    ]
