# Generated by Django 4.1.1 on 2022-12-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0004_regmodel_delete_details_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='logmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
